services:
  - type: web
    name: bitcoin-mvrv-dashboard
    env: python
    runCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
    buildCommand: pip install -r requirements.txt
